name: Sync Upstream

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1b
        with: 
          upstream_repo: https://github.com/RocketChat/Rocket.Chat
          upstream_branch: develop
          downstream_branch: develop
          token: ${{ env.GITHUB_TOKEN }}        
          UPSTREAM_REPO_PATH: https://github.com/RocketChat/Rocket.Chat
